#!/usr/bin/env bash
# Deploy KPM33B MQTT proxy on Raspberry Pi.
#
# Usage:
#   cd /opt/kpm33b_proxy
#   sudo MQTTPW="<password>" ./scripts/deploy.sh
#
# Or interactively (prompts for password):
#   cd /opt/kpm33b_proxy
#   sudo ./scripts/deploy.sh
#
# Activities requiring root:
#   - Create system user 'kpm33b'
#   - Install mosquitto package (apt-get)
#   - Disable default mosquitto systemd service
#   - Copy systemd unit files to /etc/systemd/system/
#   - Run systemctl daemon-reload, enable, start services
#   - Set ownership of /opt/kpm33b_proxy to kpm33b:kpm33b

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVICES=(kpm33b-broker kpm33b-proxy kpm33b-config-sender)
SERVICE_USER="kpm33b"

# ── Pre-checks ──────────────────────────────────────────────────────────────

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: This script must be run as root (use sudo)." >&2
    exit 1
fi

if [[ ! -f "${REPO_ROOT}/src/config.py" ]]; then
    echo "ERROR: Must be run from the repository root (expected ${REPO_ROOT}/src/config.py)." >&2
    exit 1
fi

# Get MQTT password from environment or prompt
if [[ -z "${MQTTPW:-}" ]]; then
    read -r -s -p "Enter MQTT password for central broker: " MQTTPW
    echo
fi

if [[ -z "${MQTTPW}" ]]; then
    echo "ERROR: MQTT password must not be empty." >&2
    exit 1
fi

echo "=== KPM33B Proxy Deployment ==="
echo "Repository root: ${REPO_ROOT}"

# ── Create service user (requires root) ────────────────────────────────────

echo ""
echo "--- Creating service user '${SERVICE_USER}' ---"
if id "${SERVICE_USER}" &>/dev/null; then
    echo "User '${SERVICE_USER}' already exists."
else
    useradd --system --no-create-home --shell /usr/sbin/nologin "${SERVICE_USER}"
    echo "Created system user '${SERVICE_USER}'."
fi

# ── Install system dependencies (requires root) ────────────────────────────

echo ""
echo "--- Installing mosquitto broker ---"
if command -v mosquitto >/dev/null 2>&1 || [[ -x /usr/sbin/mosquitto ]]; then
    echo "mosquitto already installed."
else
    apt-get update -qq
    apt-get install -y -qq mosquitto
fi

# Disable the default mosquitto service — we run our own via kpm33b-broker.service
if systemctl is-enabled mosquitto.service >/dev/null 2>&1; then
    echo "Disabling default mosquitto service."
    systemctl stop mosquitto.service || true
    systemctl disable mosquitto.service
fi

# ── Set up Python environment ───────────────────────────────────────────────

echo ""
echo "--- Setting up Python environment ---"
cd "${REPO_ROOT}"
bash ./init_env.sh

# ── Generate config.yaml ───────────────────────────────────────────────────

echo ""
echo "--- Generating config.yaml ---"
cat > "${REPO_ROOT}/config.yaml" <<YAML
# KPM33B Proxy Configuration — generated by deploy.sh
# Do not check into git.

internal_broker:
  host: "0.0.0.0"
  port: 11883

central_broker:
  host: ""
  port: 1883
  username: ""
  password: ""

internal_broker_topics:
  meter_seconds_data: "MQTT_RT_DATA"
  meter_minutes_data: "MQTT_ENY_NOW"
  meter_settime: "MQTT_COMMOD_SET_"
  meter_settime_ack: "MQTT_COMMOD_SET_REP"

central_broker_topics:
  external_main_topic: "kpm33b"
  status_topic: "kpm33b/status"

logging:
  level: "INFO"

kpm33b_meters:
  upload_frequency_seconds: 30
  upload_frequency_minutes: 1
YAML
chown "${SERVICE_USER}:${SERVICE_USER}" "${REPO_ROOT}/config.yaml"
chmod 600 "${REPO_ROOT}/config.yaml"
echo "config.yaml written (owner: ${SERVICE_USER}, permissions: 600)."

# ── Set ownership of repository (requires root) ────────────────────────────

echo ""
echo "--- Setting ownership of ${REPO_ROOT} ---"
chown -R "${SERVICE_USER}:${SERVICE_USER}" "${REPO_ROOT}"
echo "Ownership set to ${SERVICE_USER}:${SERVICE_USER}."

# ── Install systemd units (requires root) ──────────────────────────────────

echo ""
echo "--- Installing systemd units ---"
for svc in "${SERVICES[@]}"; do
    cp "${REPO_ROOT}/deploy/${svc}.service" "/etc/systemd/system/${svc}.service"
    echo "  installed ${svc}.service"
done
systemctl daemon-reload
echo "systemd daemon reloaded."

# ── Enable and start services (requires root) ──────────────────────────────

echo ""
echo "--- Enabling and starting services ---"
for svc in "${SERVICES[@]}"; do
    systemctl enable "${svc}.service"
    systemctl restart "${svc}.service"
    echo "  ${svc}: enabled + started"
done

# Allow services to settle
sleep 2

# ── Verify ─────────────────────────────────────────────────────────────────

echo ""
echo "--- Verification ---"
FAILED=0
for svc in "${SERVICES[@]}"; do
    if systemctl is-active --quiet "${svc}.service"; then
        echo "  ✓ ${svc} is active"
    else
        echo "  ✗ ${svc} is NOT active"
        FAILED=1
    fi
done

if ss -tlnp | grep -q ':11883 '; then
    echo "  ✓ Internal broker listening on port 11883"
else
    echo "  ✗ Internal broker NOT listening on port 11883"
    FAILED=1
fi

echo ""
if [[ ${FAILED} -eq 0 ]]; then
    echo "=== Deployment successful ==="
    echo ""
    echo "Services run as user: ${SERVICE_USER}"
    echo "View logs with: journalctl -u kpm33b-proxy"
else
    echo "=== Deployment completed with errors — check service logs: ==="
    echo "  journalctl -u kpm33b-broker --no-pager -n 20"
    echo "  journalctl -u kpm33b-proxy --no-pager -n 20"
    echo "  journalctl -u kpm33b-config-sender --no-pager -n 20"
    exit 1
fi
